### ISSUE TITLE
Wildcard principal

### ISSUE THREAD

**Issue by gabegorelick** [thinkinglabs/aws-iam-policy#22]
I don't think there's currently a way to specify `Principal: *` (please correct me if that's incorrect).

The existing `AnonymousUserPrincipal` renders to `"Principal": {"AWS": ["*"]}`, which is not exactly the same as `Principal: *`. 

See [Amazon S3 > Security > IAM > Bucket policies and user policies > Policies and permissions > Principals > Grant anonymous permissions](https://docs.aws.amazon.com/AmazonS3/latest/userguide/s3-bucket-user-policy-specifying-principal-intro.html#s3-anonymous-permissions)
See [IAM > Reference > Policy Reference > JSON element reference > Principal > All principals](https://docs.aws.amazon.com/IAM/latest/UserGuide/reference_policies_elements_principal.html#principal-anonymous)

**Comment by gabegorelick** [comment]
Additionally, calling `fromJSON` on a statement that contains `Principal: "*"` throws `Error: Unsupported principal "0"`.

**Comment by tdpauw** [comment]
Thank you @gabegorelick for this bug report.
Are you currently blocked by this problem? How urgent is this?

**Comment by gabegorelick** [comment]
I've worked around this by using `new AccountPrincipal("*")`. My understanding is that doesn't cover anonymous principals though. It's OK for now for me for the time being though, although a little suboptimal.

**Comment by tdpauw** [comment]
@gabegorelick Just so you know, I started looking into this. It is a bit more difficult than expected ...

**Comment by tdpauw** [comment]
Released v2.6.0 with a new `WildcardPrincipal`.
<https://github.com/thinkinglabs/aws-iam-policy/releases/tag/v2.6.0>
