### ISSUE TITLE
Add support for Cloudfront user principal

### ISSUE THREAD

**Issue by alejandromendeza** [thinkinglabs/aws-iam-policy#24]
It seems is not possible to parse a valid Resource Policy on a S3 bucket, such as 

```
{
    "Version": "2012-10-17",
    "Id": "PolicyForCloudFront",
    "Statement": [
        {
            "Sid": "1",
            "Effect": "Allow",
            "Principal": {
                "AWS": "arn:aws:iam::cloudfront:user/some-cloud-front-user"
            },
            "Action": "s3:GetObject",
            "Resource": "arn:aws:s3:::bucket/*"
        }
    ]
}
```
using **PolicyDocument.fromJson**, because an '**Unsupported AWS principal value "arn:aws:iam::cloudfront:user/some-cloud-front-user"**' Error is thrown

**Comment by tdpauw** [comment]
Alright, this is interesting. Thank you for reporting that!
I'll have a look at this.

**Comment by araguacaima** [comment]
I've created this PR for it

https://github.com/thinkinglabs/aws-iam-policy/pull/25
