### ISSUE TITLE
Support more than Node 16

### ISSUE THREAD

**Issue by gabegorelick** [thinkinglabs/aws-iam-policy#27]
https://github.com/thinkinglabs/aws-iam-policy/commit/6b7279df20bb5f77817e0500fe20ef51c5028987 restricted `node` in the `engines` field to `^16`. That causes many package managers to throw an error and refuse to install this package when using a different version of Node. For example, here's npm v10.7.0 on Node v20.15.1:

```
npm error code EBADENGINE
npm error engine Unsupported engine
npm error engine Not compatible with your version of node/npm: @thinkinglabs/aws-iam-policy@3.0.0
npm error notsup Not compatible with your version of node/npm: @thinkinglabs/aws-iam-policy@3.0.0
npm error notsup Required: {"node":"^16"}
npm error notsup Actual:   {"npm":"10.7.0","node":"v20.15.1"}
```

It seems like the intention behind 6b7279df20bb5f77817e0500fe20ef51c5028987 was to centralize what version of Node is used for CI, but that should not be done through `engines`.

**Comment by tdpauw** [comment]
Yes, indeed. I noticed that too. Thank you for reporting that.
