### ISSUE TITLE
PolicyDocument should allow setting Id

### ISSUE THREAD

**Issue by gabegorelick** [thinkinglabs/aws-iam-policy#29]
The `Id` element is used by some services. For example, here's a KMS key generated by CloudTrail that includes an `Id`:

<img width="483" alt="image" src="https://github.com/user-attachments/assets/7b82f212-72de-46ea-b846-4fcc61c7289e">

It's currently not possible to represent such a policy with a `PolicyDocument`. Instead, you have to convert the `PolicyDocument` to JSON and then append the `Id` field yourself.

See https://docs.aws.amazon.com/IAM/latest/UserGuide/reference_policies_elements_id.html.

**Comment by tdpauw** [comment]
Support added for Policy `Id` in v3.1.0.

https://github.com/thinkinglabs/aws-iam-policy/releases/tag/v3.1.0
