### ISSUE TITLE
It's valid for `Resource` to not be an array

### ISSUE THREAD

**Issue by danopia** [thinkinglabs/aws-iam-policy#7]
For example, `AmazonS3FullAccess` has this document:

```json
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Effect": "Allow",
      "Action": ["s3:*", "s3-object-lambda:*"],
      "Resource": "*"
    }
  ]
}
```

Trying to parse that document with this library throws:

```
error: Uncaught (in promise) Error: Unsupported type: expecting an array
      throw new Error('Unsupported type: expecting an array');
            ^
    at parseArray (aws-iam-policy/src/statement/deserialiser.ts:26:13)
    at Function.fromJSON (aws-iam-policy/src/statement/deserialiser.ts:12:18)
    at Function.fromJSON (aws-iam-policy/src/statement/statement.ts:49:38)
    at aws-iam-policy/src/policy/policy.ts:44:74
    at Array.map (<anonymous>)
    at Function.fromJson (aws-iam-policy/src/policy/policy.ts:44:40)
```

**Comment by tdpauw** [comment]
Hey, thanks a lot @danopia for reporting this issue!

You are right indeed. `Resource` can be an array as well as a string. The same is true for other elements in IAM Policy documents.
This is a known limitation of the library. I tried to document that in the Limitations section of the README.

I'll have a look at your PR #8 next week.

**Comment by danopia** [comment]
> You are right indeed. `Resource` can be an array as well as a string. The same is true for other elements in IAM Policy documents. This is a known limitation of the library. I tried to document that in the Limitations section of the README.

Ah, indeed. I have to admit that I didn't scroll down nearly far enough of the README to see that.

I handle Action and Resource in the PR I filed, because it's at the `Statement` level; I figure then that there's other places that need the same check. In practice I was processing IAM Managed Policies and my patch as-is was enough to parse through all of mine. I don't think I use "Condition" anywhere for example.

> I'll have a look at your PR #8 next week.

Thanks, sounds good!
